#
# maintain symlinks to notebooks
#

NBS = SLR_example.ipynb

# GridMapExample.ipynb


all: $(NBS)

clean:
	rm -f $(NBS)


SLR_example.ipynb:
	ln -s ../../notebooks/SLR_example.ipynb

GridMapExample.ipynb:
	ln -s ../../notebooks/GridMapExample.ipynb
