#! /usr/bin/env bash
#
#    report the LMTOY environment
#

if [ -z $LMTOY ]; then
    echo "LMTOY environment not loaded (odd)"
    exit 0
else
    echo "LMTOY:       $LMTOY  - $(cat $LMTOY/VERSION)"
fi

echo "DATA_LMT:    $DATA_LMT"
echo "WORK_LMT:    $WORK_LMT"
echo "python:      $(which python)  - $(python --version)"
echo "NEMO:        $NEMO  - $(cat $NEMO/VERSION)"
echo "lsb_release  $(lsb_release  -d)"

(cd $LMTOY; make branch)


if [ "$1" == pull ]; then
    cd $LMTOY
    make pull
fi
