#! /bin/bash
#
#    this is an example how the LMTOY environment can be installed
#    Takes about 2 mins (on a good internet connection)
#    and 4.5 GB of diskspace
#
#    28-dec-2020:     LMTSRL installed (more to come)
#     4-jan-2021:     try to be smart on finding LMT data; disable montage for now
#    12-feb-2021:     lmt_data -> data_lmt
#    23-feb-2021:     new options (venv, nemo)
#    11-may-2021:     use only $DATA_LMT, no more IRC_data
#    22-jul-2021:     better bootstrap on missing DATA_LMT
#     2-dec-2021:     add admit

version="2-dec-2021"

# set -x

lmtoy=lmtoy       # root directory name where to install (probably should not change it)
branch=master     # branch
wget=wget         # use wgetc if you have my caching version
venv=0            # set to 1 if you want to bypass a new anaconda3 and use venv
nemo=1            # set to 0 if you don't need NEMO
pgplot=1          # set to 1 if you want PGPLOT in NEMO, instead of simple PS driver
data_lmt=${DATA_LMT:-data_lmt}    # give sensible default for $DATA_LMT
work_lmt=${WORK_LMT:-work_lmt}    # give sensible default for $WORK_LMT
bench=0                           # set to the tar.gz file for bootstrapping IRC benchmark data; 0 skips
admit=1                           # install ADMIT ?
pipeline=1                        # full pipeline run on bench files? 
docs=0                            # make docs?

#             simple keyword=value command line parser for bash - don't make any changing below
for arg in $*; do\
  export $arg
done

# Announce
echo LMTOY install script version $version

# this takes about 4-5 minutes to run, including the benchmark, and takes 4.3GB

if [ -z $LMTOY ]; then
    echo "Warning, installing a new LMTOY in $lmtoy, removing the old one, if present"
    sleep 5
else
    echo "Warning, you have (an old?) LMTOY=$LMTOY loaded, this could be dangerous. Continuing at your own risk"
    sleep 5
fi

rm -rf $lmtoy

git clone https://github.com/astroumd/lmtoy $lmtoy
cd $lmtoy
git checkout $branch

#  get everything we need from github
make git

if [ $venv = 0 ]; then
  make install_python WGET=$wget
  source python_start.sh
  make pip
  make install_lmtslr
  make install_dreampy3
else
  make pip
  make install_lmtslr_venv
  make install_dreampy3_venv
fi

if [ $nemo = 1 ]; then
    echo Installing NEMO with pgplot=$pgplot
    if [ $pgplot = 1 ] ; then
	make install_nemo YAPP=pgplot
    else
	make install_nemo
    fi
fi

if [ $admit = 1 ]; then
    # for now, also install casa. sorry, linux only folks
    git clone -b python3 https://github.com/astroumd/admit
    pushd admit
    wget -O - https://casa.nrao.edu/download/distro/casa/release/el7/casa-release-5.8.0-109.el7.tar.gz | tar zxf -
    ln -s casa-release-5.8.0-109.el7 casa
    autoconf
    ./configure --with-casa-root=`pwd`/casa
    popd
fi


./configure --with-data=$(realpath $data_lmt) --with-work=$(realpath $work_lmt)

#  activate LMTOY and run benchmark, but unless you made preparations
#  on finding the data, the benchmark will not run here.

source lmtoy_start.sh
which python
python --version

if [ $docs = 1 ]; then
    (cd docs; pip3 install -r requirements.txt; make nbs lastmod html)
fi

if [ $bench != 0 ]; then
    mkdir -p $DATA_LMT
    (cd $DATA_LMT; tar zxf $bench)

    cd $LMTOY/examples

    # SLR bench
    echo Assuming your $DATA_LMT has the IRC data
    if [ -d $DATA_LMT/ifproc ]; then
	lmtinfo.py $DATA_LMT 79448 
	make bench
    else
	echo Could not find the SLR data. Hope your DATA_LMT=$DATA_LMT is good:
	ls -l $DATA_LMT
    fi

    # RSR bench
    if [ -d $DATA_LMT/rsr ]; then     
	make rsr1
    else
	echo Could not find the RSR data. Hope your DATA_LMT=$DATA_LMT is good:
	ls -l $DATA_LMT
	echo Attempting to download the RSR cal files
	(cd $DATA_LMT; make -f $LMTOY/data_lmt/Makefile rsr)
    fi
fi

# full pipeline bench for RSR and SEQ (if you pick this, the bench=1 is really not needed anymore)
if [ $pipeline = 1 ]; then
    cd $WORK_LMT
    SLpipeline.sh obsnum=33551 restart=1
    echo "QAC_STATS: rsr.33551.driver.sum.txt 2.36888e-05 0.000943648 -0.00407884 0.0459238  0 0.157781  1185 [expected]"
    echo "QAC_STATS: rsr.33551.blanking.sum.txt 4.19332e-05 0.000950482 -0.00385069 0.0459053  0 0.188981  1186 [expected]"
    SLpipeline.sh obsnum=79448 restart=1
    echo "QAC_STATS: IRC+10216_79448.ccd 0.0142744 2.21014 -563.449 634.86  0 0.0531463 [expected]"
    echo "QAC_STATS: - 0.0242549 0.33463 -2.42886 15.3425  0 0.123691 [expected]"
    echo xdg-open  $WORK_LMT/2014ARSRCommissioning/33551/README.html
    echo xdg-open  $WORK_LMT/2018S1SEQUOIACommissioning/79448/README.html
fi
